version: '3'

services:
  main_service:
    build: ./
    command: npm run start
    restart: unless-stopped
    depends_on:
      - mongo_db
    ports:
      - "3333:3333"
      - "27017:27017"
    environment:
      - PORT=3333
      - MONGO_CONNECTION=mongodb://mongo_db:27017/api

  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_db_api:/data/


volumes:
  mongo_db_api: {}
